/**
 * Product Catalog for OpenTidal
 *
 * This file contains the CTID product definitions and is maintained separately
 * from the MITRE data that is auto-generated by scripts/extract_mitre_data.py.
 *
 * Products define security telemetry sources (EDR, SIEM, firewalls, etc.)
 * with their associated data components and MITRE asset mappings.
 */

export interface Asset {
  id: string;
  vendor: string;
  productName: string;
  deployment?: string;
  description: string;
  platforms: string[];
  dataComponentIds: string[];
  mitreAssetIds?: string[];
  source: 'ctid' | 'custom' | 'ai-pending';
}

export const ctidProducts: Asset[] = [
  {
    id: 'CTID-WIN-SECURITY',
    vendor: 'Microsoft',
    productName: 'Windows Security Event Log',
    deployment: 'On-premises',
    description: 'Native Windows security auditing providing authentication, process, and privilege use events.',
    platforms: ['Windows'],
    dataComponentIds: ['DC0001', 'DC0005', 'DC0017', 'DC0036'],
    mitreAssetIds: ['ENT-WS', 'ENT-SRV', 'A0001', 'A0007'],
    source: 'ctid',
  },
  {
    id: 'CTID-SYSMON',
    vendor: 'Microsoft',
    productName: 'Sysmon',
    deployment: 'On-premises',
    description: 'Windows system service and device driver that logs detailed system activity to the Windows event log.',
    platforms: ['Windows'],
    dataComponentIds: ['DC0005', 'DC0017', 'DC0082', 'DC0024'],
    mitreAssetIds: ['ENT-WS', 'ENT-SRV', 'ENT-EP', 'A0001', 'A0007', 'A0008'],
    source: 'ctid',
  },
  {
    id: 'CTID-AZURE-ENTRA',
    vendor: 'Microsoft',
    productName: 'Azure Entra ID',
    deployment: 'Cloud',
    description: 'Cloud-based identity and access management with comprehensive sign-in and audit logging.',
    platforms: ['Identity Provider'],
    dataComponentIds: ['DC0001'],
    mitreAssetIds: ['ENT-IDM', 'ENT-CLOUD'],
    source: 'ctid',
  },
  {
    id: 'CTID-LINUX-AUDITD',
    vendor: 'Linux',
    productName: 'Auditd',
    deployment: 'On-premises',
    description: 'Linux audit daemon providing comprehensive system call and security event auditing.',
    platforms: ['Linux'],
    dataComponentIds: ['DC0001', 'DC0005', 'DC0017', 'DC0082'],
    mitreAssetIds: ['ENT-SRV', 'A0007', 'A0008'],
    source: 'ctid',
  },
  {
    id: 'CTID-CROWDSTRIKE-FALCON',
    vendor: 'CrowdStrike',
    productName: 'CrowdStrike Falcon',
    deployment: 'Cloud/Agent',
    description: 'Cloud-native endpoint protection platform providing process, network, and authentication telemetry.',
    platforms: ['Windows'],
    dataComponentIds: ['DC0005', 'DC0017', 'DC0082', 'DC0001', 'DC0024'],
    mitreAssetIds: ['ENT-WS', 'ENT-SRV', 'ENT-EP', 'A0001', 'A0002', 'A0007'],
    source: 'ctid',
  },
  {
    id: 'CTID-CISCO-MERAKI',
    vendor: 'Cisco',
    productName: 'Cisco Meraki',
    deployment: 'Cloud-managed',
    description: 'Cloud-managed networking providing network connection, firewall, and traffic flow telemetry.',
    platforms: ['Network Devices'],
    dataComponentIds: ['DC0082'],
    mitreAssetIds: ['ENT-NET', 'A0014', 'A0015', 'A0016'],
    source: 'ctid',
  },
  {
    id: 'CTID-CISCO-FIREPOWER',
    vendor: 'Cisco',
    productName: 'Cisco Firepower',
    deployment: 'On-premises/Cloud',
    description: 'Next-generation firewall and IPS providing network connection and intrusion detection telemetry.',
    platforms: ['Network Devices'],
    dataComponentIds: ['DC0082'],
    mitreAssetIds: ['ENT-NET', 'A0016'],
    source: 'ctid',
  },
  {
    id: 'CTID-AZURE-API-GATEWAY',
    vendor: 'Microsoft',
    productName: 'Azure API Gateway',
    deployment: 'Cloud',
    description: 'API management service providing API call logging, authentication events, and network connection telemetry.',
    platforms: ['IaaS'],
    dataComponentIds: ['DC0082', 'DC0001'],
    mitreAssetIds: ['ENT-CLOUD', 'A0008', 'A0009'],
    source: 'ctid',
  },
  {
    id: 'CTID-PALO-ALTO-NGFW',
    vendor: 'Palo Alto Networks',
    productName: 'Palo Alto NGFW',
    deployment: 'On-premises/Cloud',
    description: 'Next-generation firewall providing network traffic analysis, threat prevention, and URL filtering logs.',
    platforms: ['Network Devices'],
    dataComponentIds: ['DC0082'],
    mitreAssetIds: ['ENT-NET', 'A0016'],
    source: 'ctid',
  },
  {
    id: 'CTID-OKTA',
    vendor: 'Okta',
    productName: 'Okta Identity',
    deployment: 'Cloud',
    description: 'Identity and access management platform providing authentication, SSO, and MFA event logging.',
    platforms: ['Identity Provider'],
    dataComponentIds: ['DC0001'],
    mitreAssetIds: ['ENT-IDM', 'ENT-CLOUD'],
    source: 'ctid',
  },
  {
    id: 'CTID-SENTINEL-ONE',
    vendor: 'SentinelOne',
    productName: 'SentinelOne Singularity',
    deployment: 'Cloud/Agent',
    description: 'AI-powered endpoint protection providing process, file, network, and behavioral telemetry.',
    platforms: ['Windows'],
    dataComponentIds: ['DC0005', 'DC0017', 'DC0082', 'DC0024'],
    mitreAssetIds: ['ENT-WS', 'ENT-SRV', 'ENT-EP', 'A0001', 'A0007'],
    source: 'ctid',
  },
  {
    id: 'CTID-CARBON-BLACK',
    vendor: 'VMware',
    productName: 'Carbon Black EDR',
    deployment: 'Cloud/On-premises',
    description: 'Endpoint detection and response platform providing process, network, and file telemetry.',
    platforms: ['Windows'],
    dataComponentIds: ['DC0005', 'DC0017', 'DC0082'],
    mitreAssetIds: ['ENT-WS', 'ENT-SRV', 'ENT-EP', 'A0001', 'A0007'],
    source: 'ctid',
  },
  {
    id: 'CTID-DEFENDER-ENDPOINT',
    vendor: 'Microsoft',
    productName: 'Microsoft Defender for Endpoint',
    deployment: 'Cloud/Agent',
    description: 'Enterprise endpoint security platform providing process, network, file, and registry telemetry.',
    platforms: ['Windows'],
    dataComponentIds: ['DC0005', 'DC0017', 'DC0082', 'DC0001', 'DC0024', 'DC0036'],
    mitreAssetIds: ['ENT-WS', 'ENT-SRV', 'ENT-EP', 'A0001', 'A0002', 'A0007', 'A0008'],
    source: 'ctid',
  },
  {
    id: 'CTID-AWS-CLOUDTRAIL',
    vendor: 'Amazon',
    productName: 'AWS CloudTrail',
    deployment: 'Cloud',
    description: 'AWS service providing API call logging, user activity, and resource access telemetry.',
    platforms: ['IaaS'],
    dataComponentIds: ['DC0001', 'DC0082'],
    mitreAssetIds: ['ENT-CLOUD'],
    source: 'ctid',
  },
  {
    id: 'CTID-AWS-VPC-FLOW',
    vendor: 'Amazon',
    productName: 'AWS VPC Flow Logs',
    deployment: 'Cloud',
    description: 'Network flow logs capturing IP traffic going to and from network interfaces in AWS VPCs.',
    platforms: ['IaaS'],
    dataComponentIds: ['DC0082'],
    mitreAssetIds: ['ENT-CLOUD', 'ENT-NET'],
    source: 'ctid',
  },
  {
    id: 'CTID-SPLUNK-UF',
    vendor: 'Splunk',
    productName: 'Splunk Universal Forwarder',
    deployment: 'Agent',
    description: 'Log collection agent for forwarding Windows, Linux, and application logs to Splunk.',
    platforms: ['Windows'],
    dataComponentIds: ['DC0005', 'DC0017', 'DC0001', 'DC0024'],
    mitreAssetIds: ['ENT-WS', 'ENT-SRV', 'A0001', 'A0006', 'A0007'],
    source: 'ctid',
  },
  {
    id: 'CTID-ZEEK',
    vendor: 'Zeek',
    productName: 'Zeek (Bro)',
    deployment: 'On-premises',
    description: 'Open-source network analysis framework providing detailed connection, DNS, HTTP, and SSL logs.',
    platforms: ['Network Devices'],
    dataComponentIds: ['DC0082'],
    mitreAssetIds: ['ENT-NET', 'A0009'],
    source: 'ctid',
  },
  {
    id: 'CTID-SURICATA',
    vendor: 'OISF',
    productName: 'Suricata',
    deployment: 'On-premises',
    description: 'Open-source IDS/IPS providing network intrusion detection and network flow telemetry.',
    platforms: ['Network Devices'],
    dataComponentIds: ['DC0082'],
    mitreAssetIds: ['ENT-NET', 'A0016'],
    source: 'ctid',
  },
  {
    id: 'CTID-OSQUERY',
    vendor: 'osquery',
    productName: 'osquery',
    deployment: 'Agent',
    description: 'Cross-platform endpoint visibility tool providing process, network, and system state telemetry.',
    platforms: ['Linux'],
    dataComponentIds: ['DC0005', 'DC0017', 'DC0082', 'DC0001'],
    mitreAssetIds: ['ENT-SRV', 'A0007', 'A0008'],
    source: 'ctid',
  },
  {
    id: 'CTID-ELASTIC-AGENT',
    vendor: 'Elastic',
    productName: 'Elastic Agent',
    deployment: 'Agent',
    description: 'Unified agent for Elastic Security providing endpoint, network, and log telemetry.',
    platforms: ['Windows'],
    dataComponentIds: ['DC0005', 'DC0017', 'DC0082', 'DC0001', 'DC0024'],
    mitreAssetIds: ['ENT-WS', 'ENT-SRV', 'ENT-EP', 'A0001', 'A0007'],
    source: 'ctid',
  },
  {
    id: 'CTID-MACOS-ESF',
    vendor: 'Apple',
    productName: 'macOS Endpoint Security Framework',
    deployment: 'On-premises',
    description: 'Native macOS security framework providing process, file, and network event telemetry.',
    platforms: ['macOS'],
    dataComponentIds: ['DC0005', 'DC0017', 'DC0082'],
    mitreAssetIds: ['ENT-WS', 'ENT-EP'],
    source: 'ctid',
  },
  {
    id: 'CTID-FORTINET-FORTIGATE',
    vendor: 'Fortinet',
    productName: 'FortiGate',
    deployment: 'On-premises/Cloud',
    description: 'Next-generation firewall providing network security, VPN, and traffic inspection telemetry.',
    platforms: ['Network Devices'],
    dataComponentIds: ['DC0082', 'DC0001'],
    mitreAssetIds: ['ENT-NET', 'A0016', 'A0011'],
    source: 'ctid',
  },
  {
    id: 'CTID-ZSCALER',
    vendor: 'Zscaler',
    productName: 'Zscaler Internet Access',
    deployment: 'Cloud',
    description: 'Cloud security platform providing web traffic, DNS, and network connection telemetry.',
    platforms: ['Network Devices'],
    dataComponentIds: ['DC0082'],
    mitreAssetIds: ['ENT-CLOUD', 'ENT-NET', 'A0009'],
    source: 'ctid',
  },
];

/**
 * Search products by name, vendor, or platform
 */
export function searchProducts(query: string): Asset[] {
  const q = query.toLowerCase();
  return ctidProducts.filter(p =>
    p.productName.toLowerCase().includes(q) ||
    p.vendor.toLowerCase().includes(q) ||
    p.platforms.some(pl => pl.toLowerCase().includes(q))
  );
}

/**
 * Get a product by its ID
 */
export function getProductById(productId: string): Asset | undefined {
  return ctidProducts.find(p => p.id === productId);
}
